management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    prometheus:
      access: read-only
    health:
      show-details: always
      group:
        liveness:
          include: ping
        readiness:
          include: db, ping
  health:
    db:
      enabled: true

spring:
  main:
    web-application-type: servlet
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reservationdb}}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

reservation:
  auth:
    jwt-secret: ${RESERVATION_JWT_SECRET}


