management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      group:
        liveness:
          include: ping
        readiness:
          include: db, ping
  health:
    db:
      enabled: true
